apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: {{env "REPONAME"}}
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: {{env "ENV"}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: role=mongo,environment={{env "ENV"}}
            - name: KUBE_NAMESPACE
              value: {{env "REPONAME"}}
        - name: mongodb-exporter
          image: eu.gcr.io/container-registry-186614/mongodb-exporter
          imagePullPolicy: Always
          env:
            - name: MONGODB_URL
              value: mongodb://localhost:27017
          ports:
            - containerPort: 9001
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "ssd"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
