engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
      extensions:
      - .js
  fixme:
    enabled: true
  markdownlint:
    enabled: false
    issue_override:
      severity: info
#  scss-lint:
#    enabled: true
#    config:
#      config: .sass-lint.yml
  shellcheck:
    enabled: true

ratings:
  paths:
  - 'src/**.js'
#  - 'src/**.scss'
  - 'run/**.sh'

exclude_paths:
- 'assets/**'
- 'conf/**'
- 'kubefiles/**'
- 'node_modules/**'
- 'resources/**'
- 'templates/**'
- 'tmp/**'
