engines:
#  csslint:
#    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
      extensions:
      - .js
  fixme:
    enabled: true
  markdownlint:
    enabled: false
    issue_override:
      severity: info
#  scss-lint:
#    enabled: true
  shellcheck:
    enabled: true
  tslint:
    enabled: false
    channel: beta

ratings:
  paths:
#  - 'assets/**.css'
#  - 'src/**.scss'
  - 'run/**.sh'
  - 'src/**.js'

exclude_paths:
- 'assets/**'
- 'conf/**'
- 'kubefiles/**'
- 'node_modules/**'
- 'resources/**'
- 'tmp/**'
