engines:
#  csslint:
#    enabled: true
  fixme:
    enabled: true
#  markdownlint:
#    enabled: true
  sass-lint:
    enabled: true
  shellcheck:
    enabled: true
  tslint:
    enabled: false
    channel: beta

ratings:
  paths:
#  - 'assets/**.css'
#  - 'src/**.scss'
  - 'run/**.sh'

exclude_paths:
- 'assets/**'
- 'conf/**'
- 'kubefiles/**'
- 'node_modules/**'
- 'resources/**'
- 'src/test/frontend/**'
- 'tmp/**'
