version: "2"
checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 8
  method-lines:
    config:
      threshold: 40
  method-count:
    config:
      threshold: 21
  similar-code:
    enabled: false
engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
      extensions:
      - .js
  fixme:
    enabled: true
  markdownlint:
    enabled: false
    issue_override:
      severity: info
  shellcheck:
    enabled: true

ratings:
  paths:
  - 'src/**.js'
  - 'run/**.sh'

exclude_paths:
- '.circleci/**'
- 'assets/**'
- 'conf/**'
- 'kubefiles/**'
- 'node_modules/**'
- 'resources/**'
- 'templates/**'
- 'tmp/**'
- 'webpack*.js'
- '*.yml'
