# Linter Options
options:
  # Merge default rules
  merge-default-rules: true
  # Set the formatter to 'table'. Could be https://github.com/sasstools/sass-lint/blob/master/docs/options/formatter.md
  formatter: table
# File Options
files:
  include: 
  - 'src/front/scss/**/*.s+(a|c)ss'
  - 'src/admin/scss/**/*.s+(a|c)ss'

# Rule Configuration
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  
  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: true
      allow-one-empty-line: true

  single-line-per-selector: 0

  # Disallows
  no-color-keywords: 2
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 
    - 2
    -
      exclude: ['display']
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 
    - 2
    - allow-element-with-attribute: 1
    - allow-element-with-class: 1
  no-trailing-zero: 0
  no-transition-all: 0
  no-url-protocols: 0
  no-url-domains: 0
  no-vendor-prefixes: 0
  no-warn: 2

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  function-name-format: 2
  mixin-name-format: 2
  placeholder-name-format: 2
  variable-name-format:
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase

  # Style Guide
  border-zero: 2
  brace-style: 2
  clean-import-paths: 2
  empty-args: 2
  hex-length: 
    - style: long
  hex-notation: 0
  indentation: 
    - 2
    - 
      size: tab

  leading-zero: 2
  nesting-depth: 0

  property-sort-order: 0
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-around-operator: 0
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 0

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
