export const MODAL_STATE_CHANGED = 'MODAL_STATE_CHANGED';
export type MODAL_STATE_CHANGED = typeof MODAL_STATE_CHANGED;

export const MODAL_INIT = 'MODAL_INIT';
export type MODAL_INIT = typeof MODAL_INIT;

export const PROMPT_MODAL_NAME = 'PROMPT_MODAL_NAME';
export type PROMPT_MODAL_NAME = typeof PROMPT_MODAL_NAME;

export const DIALOG_MODAL_NAME = 'DIALOG_MODAL_NAME';
export type DIALOG_MODAL_NAME = typeof DIALOG_MODAL_NAME;

export const RESET_FORM_INPUT = 'RESET_FORM_INPUT';
export type RESET_FORM_INPUT = typeof RESET_FORM_INPUT;

export const USER_MODAL_NAME = 'USER_MODAL_NAME';
export type USER_MODAL_NAME = typeof USER_MODAL_NAME;

export const FIELD_MODAL_NAME = 'FIELD_MODAL_NAME';
export type FIELD_MODAL_NAME = typeof FIELD_MODAL_NAME;

export const MAIN_PRELOADER_CHANGE_STATE = 'MAIN_PRELOADER_CHANGE_STATE';
export type MAIN_PRELOADER_CHANGE_STATE = typeof MAIN_PRELOADER_CHANGE_STATE;

