jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
      - image: redis:3.2
      - image: mongo:3.0
    steps:
      - checkout
      - <<: *install_docker_compose
      - <<: *setup_remote_docker
      - <<: *docker_build
      - <<: *setup_tests
      - run:
          name: Tests
          command: |
            set -x
            docker login -u _json_key -p "$GCR_CREDENTIALS" https://eu.gcr.io
            docker-compose -f docker-compose.ci.yml up -d
            docker run --network container:app $GCR/$CIRCLE_PROJECT_REPONAME/$CIRCLE_P  ROJECT_REPONAME:$CIRCLE_SHA1 run/test --libs
            docker run --network container:app $GCR/$CIRCLE_PROJECT_REPONAME/$CIRCLE_P  ROJECT_REPONAME:$CIRCLE_SHA1 run/test --base
            docker run --network container:app $GCR/$CIRCLE_PROJECT_REPONAME/$CIRCLE_P  ROJECT_REPONAME:$CIRCLE_SHA1 run/test --app
            docker run --network container:app $GCR/$CIRCLE_PROJECT_REPONAME/$CIRCLE_P  ROJECT_REPONAME:$CIRCLE_SHA1 run/test --db
      - <<: *docker_push_gcr

  deploy_prod:  *deploy_prod
  deploy_stage: *deploy_stage
  deploy_test:  *deploy_test

workflows: *default_workflows
