jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
      - image: redis:3.2
      - image: mongo:3.0
    steps:
      - checkout
      - <<: *setup_remote_docker
      - <<: *docker_build
      - <<: *setup_tests
      - run:
          name: Show us where we are
          command: |
            env
            echo
            netstat -tlnp
            echo
      - run:
          name: Tests
          command: |
            docker run --network host -e MONGODB_URL=mongodb://localhost/readercritics -e REDIS_URL_MESSAGE_QUEUE=redis://localhost/1 -e REDIS_URL_SESSION_CACHE=redis://localhost/2 $GCR/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 -- run/test --libs
            docker run --network host -e MONGODB_URL=mongodb://localhost/readercritics -e REDIS_URL_MESSAGE_QUEUE=redis://localhost/1 -e REDIS_URL_SESSION_CACHE=redis://localhost/2 $GCR/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 -- run/test --base
            docker run --network host -e MONGODB_URL=mongodb://localhost/readercritics -e REDIS_URL_MESSAGE_QUEUE=redis://localhost/1 -e REDIS_URL_SESSION_CACHE=redis://localhost/2 $GCR/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 -- run/test --app
            docker run --network host -e MONGODB_URL=mongodb://localhost/readercritics -e REDIS_URL_MESSAGE_QUEUE=redis://localhost/1 -e REDIS_URL_SESSION_CACHE=redis://localhost/2 $GCR/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 -- run/test --db
      - <<: *docker_push_gcr

  deploy_prod:  *deploy_prod
  deploy_stage: *deploy_stage
  deploy_test:  *deploy_test

workflows: *default_workflows
