jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        environment:
        - MONGODB_URL=mongodb://localhost/readercritics
        - REDIS_URL_MESSAGE_QUEUE=redis://localhost/1
        - REDIS_URL_SESSION_CACHE=redis://localhost/2
      - image: redis:3.2
      - image: mongo:3.0
    steps:
      - checkout
      - <<: *setup_remote_docker
      - <<: *docker_build
      - <<: *setup_tests
      - run:
          name: Tests
          command: |
            run/test --libs
            run/test --base
            run/test --app
            run/test --db
      - <<: *docker_push_gcr

  deploy_prod:  *deploy_prod
  deploy_stage: *deploy_stage
  deploy_test:  *deploy_test

workflows: *default_workflows
