jobs:
  build:
    <<: *container_defaults
    steps:
      - checkout
      - <<: *setup_remote_docker
      - <<: *docker_build
      - <<: *docker_push_gcr
  deploy_prod:  *deploy_prod
  deploy_stage: *deploy_stage
  deploy_stage_from_prod: *deploy_stage
  deploy_test:  *deploy_test

workflows:
  version: 2
  main-workflow:
    jobs:
      - build:
          context: "org-global"
      - deploy_prod:
          context: "org-global"
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_stage_from_prod:
          context: "org-global"
          requires:
            - build
          filters:
            branches:
              only: master
      - approve_deploy_stage:
          context: "org-global"
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - deploy_stage:
          context: "org-global"
          requires:
            - approve_deploy_stage
          filters:
            branches:
              ignore:
                - master
