#!/usr/bin/env sh

clear

export DEBUG="*,-express:*,-finalhandler,-follow-redirects,-ioredis:*,-retry-as-promised,-send"
export NODE_ENV=${NODE_ENV:-"development"}

node --icu-data-dir=node_modules/full-icu out/start.js

