#!/usr/bin/env bash

COMMIT=$(git rev-parse --short HEAD)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

find out/ -maxdepth 1 -mindepth 1 -type d -exec rm -rf {} \;

echo -e "Version ${COMMIT} on ${BRANCH}\x0A"

checkReturnCode()
{
	if [ ${1} -ne 0 ] ; then
		echo
		echo -e "\033[1;31mAborting build\033[0m"
		exit ${1}
	fi
}

echo -e "\033[1;37mBuilding App ...\033[0m"
node_modules/.bin/tsc --pretty --diagnostics --project tsconfig.json
checkReturnCode $?

echo
echo -e "\033[1;37mBuilding Frontend ...\033[0m"
node_modules/.bin/webpack --config webpack-front.js
checkReturnCode $?

echo
echo -e "\033[1;37mBuilding Admin UI ...\033[0m"
node_modules/.bin/webpack --config webpack-admin.js
checkReturnCode $?

echo "{\"commit\":\"${COMMIT}\",\"branch\":\"${BRANCH}\"}" > out/version.json
checkReturnCode $?
