apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{env "WERCKER_GIT_REPOSITORY"}}
  namespace: {{env "WERCKER_GIT_REPOSITORY"}}
spec:
  selector: {{env "WERCKER_GIT_REPOSITORY"}}
  replicas: 2
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: {{env "WERCKER_GIT_REPOSITORY"}}
    spec:
      containers:
        - name: {{env "WERCKER_GIT_REPOSITORY"}}
          image: {{env "IMAGE"}}
          command: ["npm"]
          args: ["start"]
          ports:
          - containerPort: 4000
            name: http-port
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
          livenessProbe:
            httpGet:
              path: /api/version
              port: http-port
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/version
              port: http-port
            timeoutSeconds: 5

