apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{env "REPONAME"}}
  namespace: {{env "REPONAME"}}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{env "REPONAME"}}.{{env "ENV"}}.medialaben.no.
spec:
  tls:
  - hosts:
    - {{env "REPONAME"}}.{{env "ENV"}}.medialaben.no
    secretName: {{ env "REPONAME" }}-tls
  rules:
  - host: {{env "REPONAME"}}.{{env "ENV"}}.medialaben.no
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{env "REPONAME"}}
          servicePort: 80
