apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: internal
  name: mongo-internal
	namespace: {{env "WERCKER_GIT_REPOSITORY"}}
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    role: mongo
  sessionAffinity: None
  type: LoadBalancer
