apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: {{env "REPONAME"}}
spec:
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: {{env "ENV"}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9216"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongodb-exporter
          image: eu.gcr.io/container-registry-186614/mongodb-exporter
          env:
            - name: MONGODB_URL
              value: mongodb://mongo:27017
          ports:
            - containerPort: 9126
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "ssd"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
