apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: {{env "REPONAME"}}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: redis
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
      - name: redis-exporter
        image: oliver006/redis_exporter
        ports:
          - containerPort: 9121
