apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: {{env "REPONAME"}}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: redis
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
      - name: redis-exporter
        image: oliver006/redis_exporter
        ports:
        - name: prometheus
          containerPort: 9121
#      initContainers:
#      - name: transparent-hugepage
#        image: busybox
#        command:
#        - sh
#        - -c
#        - "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
#      - name: somaxconn
#        image: busybox
#        command:
#        - sh
#        - -c
#        - "echo 512 > /proc/sys/net/core/somaxconn"
