apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: {{env "REPONAME"}}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
      init-containers:
      - name: transparent_hugepage
        image: busybox
        command:
        - sh
        - -c
        - "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
      - name: somaxconn
        image: busybox
        command:
        - sh
        - -c
        - "echo 512 > /proc/sys/net/core/somaxconn"
