apiVersion: v1
kind: Service
metadata:
  name: reader-critics
  labels:
    app: reader-critics
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: reader-critics