apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{env "WERCKER_GIT_REPOSITORY"}}.{{env "ENV"}}.medialaben.no.
  name: {{env "WERCKER_GIT_REPOSITORY"}}
  labels:
    app: {{env "WERCKER_GIT_REPOSITORY"}}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: {{env "WERCKER_GIT_REPOSITORY"}}
