apiVersion: v1
kind: Service
metadata:
  name: {{env "WERCKER_GIT_REPOSITORY"}}
  namespace: {{env "WERCKER_GIT_REPOSITORY"}}
  labels:
    app: {{env "WERCKER_GIT_REPOSITORY"}}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: {{env "WERCKER_GIT_REPOSITORY"}}

